// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgki1qsrI3ueUhSk3sMLScb3FIziQYMnU',
    appId: '1:1019082178682:web:daebc65e29adc17ba2fbc3',
    messagingSenderId: '1019082178682',
    projectId: 'kanminabsen',
    authDomain: 'kanminabsen.firebaseapp.com',
    databaseURL: 'https://kanminabsen-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kanminabsen.appspot.com',
    measurementId: 'G-79NC1JG6NK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPiBqR0PKIgjr9VPaZovt0cVI5iq8IWIM',
    appId: '1:1019082178682:android:2fb97244755f7225a2fbc3',
    messagingSenderId: '1019082178682',
    projectId: 'kanminabsen',
    databaseURL: 'https://kanminabsen-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kanminabsen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtRcanPh9FzUJc0N8lkNA7jVmyCGoSDI0',
    appId: '1:1019082178682:ios:9ec64efb9d579214a2fbc3',
    messagingSenderId: '1019082178682',
    projectId: 'kanminabsen',
    databaseURL: 'https://kanminabsen-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kanminabsen.appspot.com',
    androidClientId: '1019082178682-p7k7jd1ajls9nkfharql8lthrv0596kb.apps.googleusercontent.com',
    iosClientId: '1019082178682-nooglt9l3hgcual4ls92odv2g1e0udmh.apps.googleusercontent.com',
    iosBundleId: 'Y',
  );
}
